### ISSUE TITLE
Add creation of `gage_counts_by_state.rds` to pipeline

### ISSUE THREAD

**Issue by lindsayplatt** [usgs-makerspace/gages-through-the-ages#147]
Currently skipped due to time constraints, so just using existing `gage_counts_by_state.rds` for now. @jread-usgs will add the code to create this. Before, he made a quick version to just unblock us from continuing to prototype the cartogram figure. It was hacked together using Colleen's gage_melt data in the gages repo but might need to adjust something in it because it was a point in polygon matching to the state

**Comment by lindsayplatt** [comment]
If we could have the column be `n_gages` instead of `n_gages_per_year` that would be awesome 👏

**Comment by jread-usgs** [comment]
so just rename the column? Or include something different in that column?

**Comment by lindsayplatt** [comment]
nope, just rename

**Comment by lindsayplatt** [comment]
Completed by #149
